language: android
sudo: true

android:
  components:
    - build-tools-23.0.2
    - android-23
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository

branches:
  only:
   - master

script:
  ./gradlew assemble
  ./gradlew assembleAndroidTest
  ./gradlew build
